"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Component_1 = require("./Component");
var Client_1 = require("./Client");
var DecoratorA_1 = require("./DecoratorA");
var DecoratorB_1 = require("./DecoratorB");
var simple = new Component_1.Component();
console.log('1. Basic component: ' + (0, Client_1.client)(simple) + '\n');
var decoratorA = new DecoratorA_1.DecoratorA(simple);
console.log('2. Decorator A: ' + (0, Client_1.client)(decoratorA) + '\n');
var decoratorB = new DecoratorB_1.DecoratorB(simple);
console.log('3. Decorator B: ' + (0, Client_1.client)(decoratorB) + '\n');
var decoratorBA = new DecoratorB_1.DecoratorB(decoratorA);
console.log('4. Decorator B-A: ' + (0, Client_1.client)(decoratorBA) + '\n');
var decoratorAB = new DecoratorA_1.DecoratorA(decoratorB);
console.log('5. Decorator A-B: ' + (0, Client_1.client)(decoratorAB) + decoratorAB.addedBehaviour() + '\n');
